#%RAML 1.0
title: Resource conversion API
version: v1
baseUri: http://api.ConversionResourceValue.com
description:
  - Resource conversion API
types:
  HierarchyPath:
    type: object
    properties:
      value: string
  HierarchyNode:
    type: object
    properties:
      name: string
      childNodes: HierarchyNode[]
/api/Nodes:
   description: Search Resource by value
   displayName: findResourceValue
   get:
     description: All value Xml information
     displayName: AllvalueXml
     responses:
       200:
        body:
         application/xml:
           type: HierarchyNode
       404:
       500:
   post:
     description: Obtain storage resources
     displayName: StorageResource
     body:
        application/json:
          type: HierarchyPath
     responses:
        200:
        500:
   /{valuename}:
      get:
        description: Get Total Value Xml information
        displayName: ValueNodeXml
        responses:
          200:
            body:
              application/xml:
                type: HierarchyNode
          404:
          500:
