#%RAML 1.0
title: Resource conversion API
version: v1
baseUri: http://api.ConversionResourceValue.com
description:
  - Resource conversion API
types:
  HierarchyPath:
    type: object
    properties:
      value: string
  HierarchyNode:
    type: object
    properties:
      name: string
      childNodes: HierarchyNode[]
/api/Node:
   description: Search Resource by value
   displayName: findResourceValue
   get:
     description: Get storage resources
     displayName:
     responses:
       200:
        body:
         application/xml:
           type: HierarchyPath
   /{value}:
      post:
        description: Get Total Data Xml information
        displayName: valueXml
        responses:
          200:
            body:
              application/xml:
                type: HierarchyNode
          404:
/Node:
   post:
      description: Get All value Xml information
      displayName: AllvalueXml
      responses:
        200:
          body:
           application/xml:
              type: HierarchyNode
        404:
