#%RAML 1.0
title: ClassifyWithTree
version: v1
baseUri: http://api.samplehost.com
protocols: HTTP
description:
  - Micro-Service to Classify data with tree
mediaType: application/xml
types:
  existData:
    type: object
    properties:
      color: string
      name: string
  Message:
    type: object
    properties:
      type: string
      content: string
  PostMessage:
    type: object
    properties:
      PostTime: datetime
      status: string
  DataList:
    type: object
    properties:
      Name: string
      Path: string


/api/Data:
  description: Data API root route
  post:
    description: post Data to service
    displayName: postData
    body:
      application/json:
        type: existData
    responses:
      200:
        body:
          application/json:
            type: PostMessage
      500:
        body:
          application/json:
            type: Message
  /NodeList:
    get:
      description: Get Data Xml information with a Node
      displayName: NodeXml
      queryParameters:
        name: string
      responses:
        200:
          body:
            application/xml:
              type: DataList
        500:
          body:
            application/json:
              type: Message
  /TotalList:
    get:
      description: Get Total Data Xml information
      displayName: TotalXml
      responses:
        200:
          body:
            application/xml:
              type: DataList
        500:
          body:
            application/json:
              type: Message
