#%RAML 1.0
title: ClassifyWithTree
version: v1
baseUri: http://api.samplehost.com
protocols: HTTP
description:
  - Micro-Service to Classify data with tree
mediaType: application/xml
types:
  Node:
    type: object
    properties:
      name: string
      childNodes: List
  DataList:
    type: object
    properties:
      Name: string
      Path: string


/api/Data:
  description: Data API root route
  post:
    description: post Data to service
    displayName: postData
    body:
      application/json:
        type: Node
    responses:
      200:
        body:
          application/json:
            type: DataList
    /{DataName}:
      get:
      description: Search Data by name
      displayName: findDataByName
      queryParameters:
        name: string
      responses:
        200:
          body:
            application/xml
              type: DataList
        404:
/api/TotalList:
    get:
      description: Get Total Data Xml information
      displayName: totalXml
      responses:
        200:
          body:
            application/xml:
              type: DataList
        404:
